In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('/Users/bhuvana/Downloads/AAK-test/books.csv', sep=',', on_bad_lines='skip')

In [5]:
print(len(df))

11123


In [7]:
df=pd.read_csv('/Users/bhuvana/Downloads/AAK-test/books.csv', sep=',',on_bad_lines='warn')

/var/folders/t_/tlj5744n231ffgjnh9bchx8h0000gq/T/ipykernel_7733/2666253562.py:1: ParserWarning: Skipping line 3350: expected 12 fields, saw 13
Skipping line 4704: expected 12 fields, saw 13
Skipping line 5879: expected 12 fields, saw 13
Skipping line 8981: expected 12 fields, saw 13

  df=pd.read_csv('/Users/bhuvana/Downloads/AAK-test/books.csv', sep=',',on_bad_lines='warn')


In [9]:
print(len(df))

11123


In [13]:
print(df[df['bookID']==3350])

Empty DataFrame
Columns: [bookID, title, authors, average_rating, isbn, isbn13, language_code,   num_pages, ratings_count, text_reviews_count, publication_date, publisher]
Index: []


4 records are missing bookID={12224, 16914, 22128, 34889} becuase those records have 13 columns(author column have ',' so that column git split to 2 for those records) intead of 12, manually adding the 4 records

In [11]:
df=pd.read_csv('/Users/bhuvana/Downloads/AAK-test/books.csv', sep=',',on_bad_lines='warn')

/var/folders/t_/tlj5744n231ffgjnh9bchx8h0000gq/T/ipykernel_7733/2666253562.py:1: ParserWarning: Skipping line 3350: expected 12 fields, saw 13
Skipping line 4704: expected 12 fields, saw 13
Skipping line 5879: expected 12 fields, saw 13
Skipping line 8981: expected 12 fields, saw 13

  df=pd.read_csv('/Users/bhuvana/Downloads/AAK-test/books.csv', sep=',',on_bad_lines='warn')


In [12]:
print(len(df))

11123


In [14]:
df.head(10)

bookID                                              title  \
0       1  Harry Potter and the Half-Blood Prince (Harry ...   
1       2  Harry Potter and the Order of the Phoenix (Har...   
2       4  Harry Potter and the Chamber of Secrets (Harry...   
3       5  Harry Potter and the Prisoner of Azkaban (Harr...   
4       8  Harry Potter Boxed Set  Books 1-5 (Harry Potte...   
5       9  Unauthorized Harry Potter Book Seven News: "Ha...   
6      10       Harry Potter Collection (Harry Potter  #1-6)   
7      12  The Ultimate Hitchhiker's Guide: Five Complete...   
8      13  The Ultimate Hitchhiker's Guide to the Galaxy ...   
9      14  The Hitchhiker's Guide to the Galaxy (Hitchhik...   

                      authors  average_rating        isbn         isbn13  \
0  J.K. Rowling/Mary GrandPré            4.57  0439785960  9780439785969   
1  J.K. Rowling/Mary GrandPré            4.49  0439358078  9780439358071   
2                J.K. Rowling            4.42  0439554896  9780439554893   
3  J.K. Rowling/Mary GrandPré            4.56  043965548X  9780439655484   
4  J.K. Rowling/Mary GrandPré            4.78  0439682584  9780439682589   
5      W. Frederick Zimmerman            3.74  0976540606  9780976540601   
6                J.K. Rowling            4.73  0439827604  9780439827607   
7               Douglas Adams            4.38  0517226952  9780517226957   
8               Douglas Adams            4.38  0345453743  9780345453747   
9               Douglas Adams            4.22  1400052920  9781400052929   

  language_code    num_pages  ratings_count  text_reviews_count  \
0           eng          652        2095690               27591   
1           eng          870        2153167               29221   
2           eng          352           6333                 244   
3           eng          435        2339585               36325   
4           eng         2690          41428                 164   
5         en-US          152             19                   1   
6           eng         3342          28242                 808   
7           eng          815           3628                 254   
8           eng          815         249558                4080   
9           eng          215           4930                 460   

  publication_date        publisher  
0        9/16/2006  Scholastic Inc.  
1         9/1/2004  Scholastic Inc.  
2        11/1/2003       Scholastic  
3         5/1/2004  Scholastic Inc.  
4        9/13/2004       Scholastic  
5        4/26/2005     Nimble Books  
6        9/12/2005       Scholastic  
7        11/1/2005   Gramercy Books  
8        4/30/2002    Del Rey Books  
9         8/3/2004            Crown

In [15]:
df.isnull().sum()

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

In [16]:
df[df['bookID'].isin([31373,45531])]

bookID                                              title  \
8177    31373  In Pursuit of the Proper Sinner (Inspector Lyn...   
11094   45531         Montaillou  village occitan de 1294 à 1324   

                                               authors  average_rating  \
8177                                 Elizabeth  George            4.10   
11094  Emmanuel Le Roy Ladurie/Emmanuel Le Roy-Ladurie            3.96   

             isbn         isbn13 language_code    num_pages  ratings_count  \
8177   0553575104  9780553575101           eng          718          10608   
11094  2070323285  9782070323289           fre          640             15   

       text_reviews_count publication_date       publisher  
8177                  295       11/31/2000    Bantam Books  
11094                   2        6/31/1982  Folio histoire

In [17]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.dtypes

bookID                  int64
title                  object
authors                object
average_rating        float64
isbn                   object
isbn13                  int64
language_code          object
  num_pages             int64
ratings_count           int64
text_reviews_count      int64
publication_date       object
publisher              object
dtype: object

In [20]:
len(df)

11123

In [26]:
df['title']=df['title'].astype('string')

In [27]:
df['authors']=df['authors'].astype('string')
df['language_code']=df['language_code'].astype('string')

In [28]:
df.dtypes

bookID                         int64
title                 string[python]
authors               string[python]
average_rating               float64
isbn                          object
isbn13                         int64
language_code         string[python]
  num_pages                    int64
ratings_count                  int64
text_reviews_count             int64
publication_date              object
publisher                     object
dtype: object

In [42]:
df['publication_date'] = pd.to_datetime(df['publication_date'], errors='coerce')

In [43]:
df.dtypes

bookID                         int64
title                 string[python]
authors               string[python]
average_rating               float64
isbn                          object
isbn13                         int64
language_code         string[python]
  num_pages                    int64
ratings_count                  int64
text_reviews_count             int64
publication_date      datetime64[ns]
publisher                     object
dtype: object

In [44]:
len(df)

11123

In [46]:
df['average_rating'] = df['average_rating'].apply(lambda x: f"{x:.2f}")

In [50]:
print(df[df['bookID']==25])

    bookID                                              title      authors  \
16      25  I'm a Stranger Here Myself: Notes on Returning...  Bill Bryson   

   average_rating        isbn         isbn13 language_code    num_pages  \
16           3.90  076790382X  9780767903820           eng          304   

    ratings_count  text_reviews_count publication_date       publisher  
16          49240                2211       2000-06-28  Broadway Books  


In [51]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', '  num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='object')

In [53]:
df=df.rename(columns={'  num_pages':'num_pages'})

In [54]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', 'num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='object')

In [55]:
len(df)

11123

In [56]:
null_values=df[df.isnull().any(axis=1)]
print(null_values)

       bookID                                              title  \
8177    31373  In Pursuit of the Proper Sinner (Inspector Lyn...   
11094   45531         Montaillou  village occitan de 1294 à 1324   

                                               authors average_rating  \
8177                                 Elizabeth  George           4.10   
11094  Emmanuel Le Roy Ladurie/Emmanuel Le Roy-Ladurie           3.96   

             isbn         isbn13 language_code  num_pages  ratings_count  \
8177   0553575104  9780553575101           eng        718          10608   
11094  2070323285  9782070323289           fre        640             15   

       text_reviews_count publication_date       publisher  
8177                  295              NaT    Bantam Books  
11094                   2              NaT  Folio histoire  


the dates are not read for bookID's 31373(11/31/2000) and 45531(6/31/1982), manually adding the values as there is some issue with that information

In [60]:
df.to_csv('transformed_books.csv', index=False)

In [61]:
df.describe

<bound method NDFrame.describe of        bookID                                              title  \
0           1  Harry Potter and the Half-Blood Prince (Harry ...   
1           2  Harry Potter and the Order of the Phoenix (Har...   
2           4  Harry Potter and the Chamber of Secrets (Harry...   
3           5  Harry Potter and the Prisoner of Azkaban (Harr...   
4           8  Harry Potter Boxed Set  Books 1-5 (Harry Potte...   
...       ...                                                ...   
11118   45631   Expelled from Eden: A William T. Vollmann Reader   
11119   45633                        You Bright and Risen Angels   
11120   45634                    The Ice-Shirt (Seven Dreams #1)   
11121   45639                                        Poor People   
11122   45641                        Las aventuras de Tom Sawyer   

                                                 authors average_rating  \
0                             J.K. Rowling/Mary GrandPré           4.57   

In [63]:
df[df['bookID']==38338]

bookID title                                            authors  \
9606   38338  9-11  Noam Chomsky/Greg Ruggiero/Marili Margomenou/M...   

     average_rating        isbn         isbn13 language_code  num_pages  \
9606           3.73  1583224890  9781583224892           eng        140   

      ratings_count  text_reviews_count publication_date            publisher  
9606           3070                 172       2001-12-04  Seven Stories Press

In [65]:
df[df['bookID']==38338]['authors']

9606    Noam Chomsky/Greg Ruggiero/Marili Margomenou/M...
Name: authors, dtype: string

In [66]:
df['title']=df['title'].replace('9-11','Sep-11')

In [67]:
df[df['bookID']==38338]

bookID   title                                            authors  \
9606   38338  Sep-11  Noam Chomsky/Greg Ruggiero/Marili Margomenou/M...   

     average_rating        isbn         isbn13 language_code  num_pages  \
9606           3.73  1583224890  9781583224892           eng        140   

      ratings_count  text_reviews_count publication_date            publisher  
9606           3070                 172       2001-12-04  Seven Stories Press

In [77]:
df.loc[df['bookID']==31373, 'publication_date'] ='11/31/2000'

In [78]:
df[df['bookID']==31373]

bookID                                              title  \
8177   31373  In Pursuit of the Proper Sinner (Inspector Lyn...   

                authors average_rating        isbn         isbn13  \
8177  Elizabeth  George           4.10  0553575104  9780553575101   

     language_code  num_pages  ratings_count  text_reviews_count  \
8177           eng        718          10608                 295   

     publication_date     publisher  
8177       11/31/2000  Bantam Books

In [79]:
df.loc[df['bookID']==45531, 'publication_date'] ='6/31/1982'

In [80]:
df[df['bookID']==45531]

bookID                                       title  \
11094   45531  Montaillou  village occitan de 1294 à 1324   

                                               authors average_rating  \
11094  Emmanuel Le Roy Ladurie/Emmanuel Le Roy-Ladurie           3.96   

             isbn         isbn13 language_code  num_pages  ratings_count  \
11094  2070323285  9782070323289           fre        640             15   

       text_reviews_count publication_date       publisher  
11094                   2        6/31/1982  Folio histoire

In [81]:
len(df)

11123

In [87]:
df[df['bookID']==26012]

bookID      title                               authors average_rating  \
6900   26012  Glamorama  Bret Easton Ellis/Pierre Guglielmina           3.46   

            isbn         isbn13 language_code  num_pages  ratings_count  \
6900  2264031913  9782264031914           fre        537             56   

      text_reviews_count     publication_date publisher  
6900                   5  2001-02-15 00:00:00     10/18

In [89]:
df['publisher']=df['publisher'].replace('10/18', 'Edisions 10/18')

In [90]:
df[df['bookID']==26012]

bookID      title                               authors average_rating  \
6900   26012  Glamorama  Bret Easton Ellis/Pierre Guglielmina           3.46   

            isbn         isbn13 language_code  num_pages  ratings_count  \
6900  2264031913  9782264031914           fre        537             56   

      text_reviews_count     publication_date       publisher  
6900                   5  2001-02-15 00:00:00  Edisions 10/18

In [91]:
df[df['bookID']==28225]

bookID         title          authors average_rating        isbn  \
7325   28225  La mezzanine  Nicholson Baker           3.84  2264017694   

             isbn13 language_code  num_pages  ratings_count  \
7325  9782264017697           fre        191              6   

      text_reviews_count     publication_date       publisher  
7325                   1  1998-11-18 00:00:00  Edisions 10/18

In [94]:
df.to_csv('transformed_data.csv', index=False)

Transformation of data completed after loading the missing 4 records as well. Now loading the data to Sqlite3 database